### DISCUSSION TITLE
Action has quite working

### DISCUSSION THREAD

**Discussion by Emerald-Void** [DenverCoder1/github-readme-youtube-cards#170] [Q&A]
So, when I added the .yml file to my page, it worked once and has never updated. When I check it to see why, I get the following error:

- github Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

I don't know anything about node.js so I'm not sure how to fix this. 

I've followed the link provided in the error and I'm still not sure how to fix it.

This is my code 

```
name: GitHub Readme YouTube Cards

on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: **channel ID here**
          show_duration: true
```

How do I need to fix this?
