### ISSUE TITLE
🚀 Feature: Throw Error if the videos still the same to prevent unnecessary commit/update

### ISSUE THREAD

**Issue by ImBIOS** [DenverCoder1/github-readme-youtube-cards#106]
### Description

Hi everyone, I was hoping to suggest a new feature for DenverCoder1's GitHub Readme YouTube Cards. I think it would be great if the plugin could throw an error if a user tries to add a YouTube video to their README.md file that already exists, in order to prevent unnecessary commits or updates.

With this feature, the plugin would check if the video ID that the user is trying to add already exists in the README.md file. If it does, the plugin would throw an error and prevent the user from committing or updating the file with the same video again. This would help prevent clutter and unnecessary updates to the README.md file, making it easier to maintain and read.

I believe the addition of this feature would save users time by preventing them from manually checking if a video ID already exists in the README.md file before adding it. With this feature in place, users can be confident that their README.md file is always up-to-date and accurate, without the need for manual checks or redundant updates.

If you agree that this feature would be useful, I would appreciate it if you could support my request by leaving a comment or reaction on this issue. Also, feel free to suggest any additional requirements or considerations for the implementation of this feature, such as error messaging or any potential edge cases to be aware of. Thank you for your time and consideration.

**Comment by DenverCoder1** [comment]
I'm not sure I fully understand.

The add-and-commit step of the workflow already does not create a commit if there are no changes to be made.

There is no need to manually modify the readme since running the workflow on a schedule or with the dispatch button will always ensure it's up to date and create a commit to update it if it's not.

New video IDs are not the only thing that can trigger, if a title is edited, it will also cause a new commit since the title is displayed in the readme.

**Comment by ImBIOS** [comment]
I'd love to have a feature to enable/disable errors on no update detected. So, we can track if there is no update in YT. Because it'll be a notification for failed workflow.

**Comment by DenverCoder1** [comment]
Why would you want a notification when nothing has changed?

**Comment by ImBIOS** [comment]
Maybe, to remind me if I forgot to make a video (?)
I'd love to working on this if you assign me tho :)

**Comment by DenverCoder1** [comment]
I think maybe a separate workflow or a calendar app would be better as I feel it is out of the scope of the project since the purpose is just to display videos.

What I have considered as a possible solution to this issue is that we could add as an output whether or not it pushed to the repo (we can get this info from the outputs of add-and-commit - https://github.com/EndBug/add-and-commit#outputs).

This would still keep the code more focused to the task and be more flexible for allowing people to extend the workflow by using the `pushed` output after github-readme-youtube-cards to send notifications or anything else the user of the workflow chooses.

**Comment by ImBIOS** [comment]
I think it's a better idea and makes the code cleaner by using the existing dependency feature.

**Comment by DenverCoder1** [comment]
The commited and pushed status is now an output of the action. What I'd recommend for your use case is to check if the YouTube cards action committed using a separate step, for example:

```yml
name: GitHub Readme YouTube Cards
on: ...

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        id: youtube-cards
        with:
          channel_id: UCipSxT7a3rn81vGLw9lqRkg
        
      # fail if not committed
      - if : ${{ steps.youtube-cards.outputs.committed == 'false' }}
        run: exit 1
```

**Comment by ImBIOS** [comment]
Thanks! Here is my action:

```yml
name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: '0 0 1 * *' # Run at 00:00 on the first day of every month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        id: youtube-cards
        with:
          channel_id: UCHadELD-gro_9fm47EJrcUw
      - if: ${{ steps.youtube-cards.outputs.committed == 'false' }}
        run: echo "No new youtube video in the past month!"; exit 1;
```
